### PR TITLE
update gradle

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Updates gradle to work with latest version.  Tested on gradle 7+

### CODE REVIEW

**Comment by yuliumitre** [comment]
@KeeyanGhoreshi what is the gradle version required for this PR? Do you need to update the README?

**Comment by KeeyanGhoreshi** [comment]
I don't believe there is a required gradle version, it should work with older versions of gradle.

**Comment by yuliumitre** [comment]
> I don't believe there is a required gradle version, it should work with older versions of gradle.

Right, it works with older version of gradle. 

In CRD set up: https://github.com/HL7-DaVinci/CRD#prerequisites we are saying gradle 6.3. In gradle wrapper, the setting is for gradle 7.2. 

@plarocque4 Pat, is the wrapper used by the Logica Server to start CRD? Thanks.

**Comment by plarocque4** [comment]
> > I don't believe there is a required gradle version, it should work with older versions of gradle.
> 
> Right, it works with older version of gradle.
> 
> In CRD set up: https://github.com/HL7-DaVinci/CRD#prerequisites we are saying gradle 6.3. In gradle wrapper, the setting is for gradle 7.2.
> 
> @plarocque4 Pat, is the wrapper used by the Logica Server to start CRD? Thanks.

I am not sure what the wrapper is for. It does look like the Dockerfile is using Gradle 6.9 and we should probably update that at some point too.

**Review by yuliumitre — APPROVED** [review]

**Pull request merged**
