### PR TITLE
Logica Fix

### PR DESCRIPTION
**Pull request by plarocque4**
Update TokenResponse to rename patient to patientId as it should be.
Need to coordinate this with the crd-request-generator and dtr fixes.

### CODE REVIEW

**Review by KeeyanGhoreshi — CHANGES_REQUESTED** [review]
I believe the EHR also needs a change to the launchId to work with the EHR, should be in `AuthResponse`, the variable name needs to be changed as well.

**Comment by plarocque4** [comment]
> I believe the EHR also needs a change to the launchId to work with the EHR, should be in `AuthResponse`, the variable name needs to be changed as well.

Which value in the AuthResponse? The only value is launchId. What should that be changed to?

**Comment by KeeyanGhoreshi** [comment]
i think it's supposed to be launch_id now

**Comment by plarocque4** [comment]
That would be an easy change, but what would I do to test it to make sure it works?

**Comment by KeeyanGhoreshi** [comment]
run the `logica fix` branch of the apps and make sure you can run the DTR app using our test-ehr

**Review by KeeyanGhoreshi — APPROVED** [review]
works, lgtm

**Pull request merged**
