### PR TITLE
Support newer versions of Keycloak

### PR DESCRIPTION
**Pull request by plarocque4**
Update the KeyCloak auth realm to work with newer versions of keycloak that require the scope to be specified.

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
When I make a new realm and try importing this file it doesn't load the scopes.  I'm not sure why, they are included in the json.

**Comment by plarocque4** [comment]
> When I make a new realm and try importing this file it doesn't load the scopes. I'm not sure why, they are included in the json.

Which version of Keycloak are you using? I didn't have any problems when I had done it in multiple different releases.

**Comment by KeeyanGhoreshi** [comment]
Keycloak 15.0.2, I create a new realm and import the json, it adds the clients but it does not add the scopes.

**Comment by plarocque4** [comment]
> Works after deleting my previous ClientFhirServer realm. This might be worth mentioning in the readme, to inform people that upgrading their existing keycloak instance might cause errors, and that they should delete their existing instance and redo the steps to create a user. For most cases it won't be relevant, though.

I updated the readme in CRD with details about that and made a new pull request 
https://github.com/HL7-DaVinci/CRD/pull/268

**Pull request merged**
